"""
FastAPI application for EHR Timeline Triage.

Serves predictions through REST API.

⚠️ RESEARCH USE ONLY - NOT FOR CLINICAL DECISION MAKING ⚠️
"""

from fastapi import FastAPI, HTTPException
from fastapi.middleware.cors import CORSMiddleware
from fastapi.responses import JSONResponse

from api.routers import predict
from ehrtriage import __version__

# Create app
app = FastAPI(
    title="EHR Timeline Triage API",
    description=(
        "AI-powered risk prediction from EHR timelines.\n\n"
        "⚠️ **RESEARCH PROTOTYPE ONLY - NOT FOR CLINICAL USE** ⚠️\n\n"
        "This API provides risk predictions for:\n"
        "- 30-day readmission\n"
        "- 48-hour ICU mortality\n\n"
        "All predictions are generated by machine learning models trained on "
        "synthetic or deidentified data and should NOT be used for clinical "
        "decision-making."
    ),
    version=__version__,
)

# CORS middleware (allow all origins for development)
app.add_middleware(
    CORSMiddleware,
    allow_origins=["*"],  # In production, specify exact origins
    allow_credentials=True,
    allow_methods=["*"],
    allow_headers=["*"],
)


# Include routers
app.include_router(predict.router, prefix="/api", tags=["Predictions"])


@app.get("/")
async def root():
    """Root endpoint with disclaimer."""
    return {
        "name": "EHR Timeline Triage API",
        "version": __version__,
        "status": "running",
        "disclaimer": (
            "⚠️ RESEARCH PROTOTYPE ONLY - NOT FOR CLINICAL USE ⚠️ "
            "This system is for research and educational purposes only. "
            "Do not use for patient care or clinical decisions."
        ),
        "endpoints": {
            "docs": "/docs",
            "predict_readmission": "/api/predict/readmission",
            "predict_icu_mortality": "/api/predict/icu_mortality",
            "available_models": "/api/models",
        },
    }


@app.get("/health")
async def health():
    """Health check endpoint."""
    return {"status": "healthy"}


if __name__ == "__main__":
    import uvicorn

    uvicorn.run(app, host="0.0.0.0", port=8000)
